name: Hello World!
on:
  push:
    branches:
      - master
jobs:
  init_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: initial
        run: |
          echo "initial !"
      - name: Now it is
        run: |
          date
      - name: Directory Content
        run: |
          ls
          